services:
  - postgresql

before_script:
  - psql -c 'create database expensify_test;' -U postgres  

language: ruby

rvm:
  - 2.2.5

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails test